services:
  flask-app:
    image: python:3.10
    command: bash -c "cd app/ && pip install -r requirements.txt && python app.py"
    environment:
      - SUBSCRIPTION_KEY="sua chave sem aspas aqui"
      - ENDPOINT="seu endpoint sem aspas aqui"
      - MONGO_URI=${MONGO_URI}
      #- MONGO_URI=mongodb://root:example@mongodb:27017/flaskdb?authSource=admin
    volumes:
      - ./backend_v2:/app
    ports:
      - "5000:5000"
    restart: always
    networks:
      - my_custom_network
  frontend:
    container_name: textgrader_frontend
    image: node:lts-alpine
    working_dir: "/frontend"
    command: sh -c "yarn && yarn prod"
    ports:
      - 3000:3000
    depends_on:
      - flask-app
    volumes:
      - ./frontend:/frontend
    restart: always
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge