services:
  flask-app:
    image: python:3.10
    command: bash -c "cd app/ && pip install -r requirements.txt && python app.py"
    environment:
      - SUBSCRIPTION_KEY="sua chave sem aspas aqui"
      - ENDPOINT="seu endpoint sem aspas aqui"
      - MONGO_URI=${MONGO_URI}
      - OLLAMA_HOST=ollama
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    restart: always
    networks:
      - my_custom_network

  frontend:
    container_name: lumen_frontend
    image: node:lts-alpine
    working_dir: "/frontend"
    command: sh -c "yarn && yarn prod"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    restart: always
    networks:
      - my_custom_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: serve
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - my_custom_network
    restart: unless-stopped
    depends_on:
      - flask-app
      - frontend

networks:
  my_custom_network:
    driver: bridge

volumes:
  ollama_data:
